import { readFile, writeFile, stat } from "node:fs/promises";
import { resolve, relative, basename, join } from "node:path";
import type { InputDeclaration } from "../core/types.js";

// ---- .markflow.json --------------------------------------------------------

export interface MarkflowJson {
  workflow: string; // path relative to workspace dir
}

export async function readMarkflowJson(
  workspaceDir: string,
): Promise<MarkflowJson | null> {
  try {
    const raw = await readFile(join(workspaceDir, ".markflow.json"), "utf-8");
    return JSON.parse(raw) as MarkflowJson;
  } catch {
    return null;
  }
}

export async function writeMarkflowJson(
  workspaceDir: string,
  relativeWorkflow: string,
): Promise<void> {
  const data: MarkflowJson = { workflow: relativeWorkflow };
  await writeFile(
    join(workspaceDir, ".markflow.json"),
    JSON.stringify(data, null, 2) + "\n",
    "utf-8",
  );
}

// ---- Target resolution -----------------------------------------------------

export interface ResolvedTarget {
  workflowPath: string; // absolute path to workflow .md
  workspaceDir: string; // absolute path to workspace folder
  workspaceExists: boolean;
}

/**
 * Resolve a CLI target (either a workflow .md path or a workspace directory)
 * into absolute workflow + workspace paths.
 *
 * Rules:
 *   - Existing directory  → workspace mode; reads .markflow.json for workflow
 *   - *.md path           → workflow mode; workspace = --workspace or ./<stem>
 *   - Anything else       → error
 */
export async function resolveTarget(
  target: string,
  workspaceFlag?: string,
): Promise<ResolvedTarget> {
  const absTarget = resolve(target);

  // Check if it's an existing directory
  let targetStat: Awaited<ReturnType<typeof stat>> | null = null;
  try {
    targetStat = await stat(absTarget);
  } catch {
    /* doesn't exist */
  }

  if (targetStat?.isDirectory()) {
    const wsData = await readMarkflowJson(absTarget);
    if (!wsData) {
      throw new Error(
        `"${target}" is not a markflow workspace — no .markflow.json found.\n` +
          `Run: markflow init <workflow.md> --workspace ${target}`,
      );
    }
    const workflowPath = resolve(absTarget, wsData.workflow);
    return { workflowPath, workspaceDir: absTarget, workspaceExists: true };
  }

  if (!absTarget.endsWith(".md")) {
    throw new Error(
      `"${target}" is neither a .md workflow file nor an existing workspace directory`,
    );
  }

  // Target is a workflow file — derive workspace
  const stem = basename(absTarget, ".md");
  const workspaceDir = resolve(workspaceFlag ?? `./${stem}`);

  let workspaceExists = false;
  try {
    const wsStat = await stat(workspaceDir);
    workspaceExists = wsStat.isDirectory();
  } catch {
    /* doesn't exist */
  }

  return { workflowPath: absTarget, workspaceDir, workspaceExists };
}

// ---- .env generation -------------------------------------------------------

/**
 * Generate .env content for a new workspace.
 * - Inputs with a provided value → active (KEY=value)
 * - Inputs with a default         → commented with default (# KEY=default)
 * - All other inputs              → empty placeholder (# KEY=)
 */
export function generateEnvContent(
  workflowName: string,
  inputs: InputDeclaration[],
  provided: Record<string, string>,
): string {
  const lines: string[] = [
    `# Generated by markflow init — ${workflowName}`,
    `# Uncomment and fill in required values.`,
    ``,
  ];

  for (const inp of inputs) {
    if (inp.name in provided) {
      lines.push(`${inp.name}=${provided[inp.name]}`);
    } else if (inp.default !== undefined) {
      lines.push(`# ${inp.name}=${inp.default}`);
    } else {
      lines.push(`# ${inp.name}=`);
    }
  }

  return lines.join("\n") + "\n";
}

// ---- .env update (additive) ------------------------------------------------

const KEY_RE = /^([A-Z_][A-Z0-9_]*)=(.*)$/;
const COMMENTED_KEY_RE = /^#\s*([A-Z_][A-Z0-9_]*)=(.*)$/;

/**
 * Update existing .env content.
 *
 * Rules (additive by default):
 *   - Lines for keys in `provided`  → made active with new value
 *   - Inputs in `inputs` not in file → appended as commented placeholders
 *   - Unknown keys not in `inputs`  → preserved unless `remove` is true
 *   - `remove: true`                → drops lines for keys absent from `inputs`
 */
export function updateEnvContent(
  existing: string,
  inputs: InputDeclaration[],
  provided: Record<string, string>,
  remove: boolean,
): string {
  const workflowKeys = new Set(inputs.map((i) => i.name));
  const defaultMap = new Map(
    inputs.filter((i) => i.default !== undefined).map((i) => [i.name, i.default!]),
  );

  const fileKeys = new Set<string>();
  const existingLines = existing.split("\n");

  const updatedLines: string[] = [];
  for (const line of existingLines) {
    const activeMatch = KEY_RE.exec(line);
    const commentedMatch = !activeMatch ? COMMENTED_KEY_RE.exec(line) : null;
    const key = activeMatch?.[1] ?? commentedMatch?.[1];

    if (!key) {
      updatedLines.push(line);
      continue;
    }

    fileKeys.add(key);

    // Drop if --remove and not in this workflow's inputs
    if (remove && !workflowKeys.has(key)) continue;

    // Apply provided value
    if (key in provided) {
      updatedLines.push(`${key}=${provided[key]}`);
      continue;
    }

    updatedLines.push(line);
  }

  // Append inputs not already in the file
  const newInputs = inputs.filter((i) => !fileKeys.has(i.name));
  if (newInputs.length > 0) {
    updatedLines.push("");
    for (const inp of newInputs) {
      if (inp.name in provided) {
        updatedLines.push(`${inp.name}=${provided[inp.name]}`);
      } else if (defaultMap.has(inp.name)) {
        updatedLines.push(`# ${inp.name}=${defaultMap.get(inp.name)}`);
      } else {
        updatedLines.push(`# ${inp.name}=`);
      }
    }
  }

  return updatedLines.join("\n");
}

// ---- Input parsing from --input flags --------------------------------------

export function parseInputFlags(flags: string[] | undefined): Record<string, string> {
  const result: Record<string, string> = {};
  for (const entry of flags ?? []) {
    const eq = entry.indexOf("=");
    if (eq === -1) throw new Error(`Invalid --input value "${entry}": expected KEY=VALUE`);
    result[entry.slice(0, eq)] = entry.slice(eq + 1);
  }
  return result;
}

// ---- Relative path helper --------------------------------------------------

/** Relative path from workspaceDir to workflowPath, normalised with forward slashes. */
export function workflowRelativePath(
  workspaceDir: string,
  workflowPath: string,
): string {
  return relative(workspaceDir, workflowPath).replace(/\\/g, "/");
}
