import { describe, it, expect } from "vitest";
import { generateEnvContent, updateEnvContent, parseInputFlags } from "../../src/cli/workspace.js";
import type { InputDeclaration } from "../../src/core/types.js";

const inputs: InputDeclaration[] = [
  { name: "PLANE_URL", required: false, default: "https://app.plane.so", description: "Base URL" },
  { name: "PLANE_API_KEY", required: true, description: "API key" },
  { name: "WORKSPACE_SLUG", required: true, description: "Workspace slug" },
];

describe("generateEnvContent", () => {
  it("comments out inputs without a provided value", () => {
    const content = generateEnvContent("My Workflow", inputs, {});
    expect(content).toContain("# PLANE_URL=https://app.plane.so");
    expect(content).toContain("# PLANE_API_KEY=");
    expect(content).toContain("# WORKSPACE_SLUG=");
  });

  it("writes provided values as active lines", () => {
    const content = generateEnvContent("My Workflow", inputs, {
      WORKSPACE_SLUG: "my-ws",
    });
    expect(content).toContain("WORKSPACE_SLUG=my-ws");
    expect(content).not.toMatch(/^PLANE_API_KEY=/m);
  });

  it("includes a header comment with the workflow name", () => {
    const content = generateEnvContent("Plane Ticket Analysis", inputs, {});
    expect(content).toContain("Plane Ticket Analysis");
  });
});

describe("updateEnvContent", () => {
  const existing = [
    "# Generated by markflow init — My Workflow",
    "# PLANE_URL=https://app.plane.so",
    "WORKSPACE_SLUG=old-value",
    "# PLANE_API_KEY=",
  ].join("\n");

  it("updates an active value", () => {
    const result = updateEnvContent(existing, inputs, { WORKSPACE_SLUG: "new-value" }, false);
    expect(result).toContain("WORKSPACE_SLUG=new-value");
    expect(result).not.toContain("WORKSPACE_SLUG=old-value");
  });

  it("activates a previously commented key", () => {
    const result = updateEnvContent(existing, inputs, { PLANE_API_KEY: "secret" }, false);
    expect(result).toContain("PLANE_API_KEY=secret");
    expect(result).not.toMatch(/^# PLANE_API_KEY=/m);
  });

  it("is additive: unknown keys are preserved by default", () => {
    const withExtra = existing + "\nEXTRA_KEY=keep-me";
    const result = updateEnvContent(withExtra, inputs, {}, false);
    expect(result).toContain("EXTRA_KEY=keep-me");
  });

  it("removes keys not in workflow when --remove is set", () => {
    const withExtra = existing + "\nEXTRA_KEY=remove-me";
    const result = updateEnvContent(withExtra, inputs, {}, true);
    expect(result).not.toContain("EXTRA_KEY");
  });

  it("appends new inputs not present in existing file", () => {
    const noSlug = existing.replace(/.*WORKSPACE_SLUG.*\n?/, "");
    const result = updateEnvContent(noSlug, inputs, {}, false);
    expect(result).toContain("WORKSPACE_SLUG");
  });

  it("preserves pure comment lines and blank lines", () => {
    const result = updateEnvContent(existing, inputs, {}, false);
    expect(result).toContain("# Generated by markflow init");
  });
});

describe("parseInputFlags", () => {
  it("parses KEY=VALUE pairs", () => {
    expect(parseInputFlags(["FOO=bar", "BAZ=qux"])).toEqual({ FOO: "bar", BAZ: "qux" });
  });

  it("handles values containing =", () => {
    expect(parseInputFlags(["URL=https://a.b?x=1"])).toEqual({ URL: "https://a.b?x=1" });
  });

  it("throws on missing = sign", () => {
    expect(() => parseInputFlags(["INVALID"])).toThrow("KEY=VALUE");
  });

  it("returns empty record for undefined", () => {
    expect(parseInputFlags(undefined)).toEqual({});
  });
});
